apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: newsapp
  name: newsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newsapp
  template:
    metadata:
      labels:
        app: newsapp
        role: rolling-update
    spec:
      containers:
      - image: princejoseph1k94/newsapp:{{BUILD_NUMBER}}
        name: newsapp
        resources: {}
        ports:
        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /
            port: 8090
  strategy:
    type: RollingUpdate